version: "3"
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=travis_ci_test
      - POSTGRES_USER=travis_ci_test
      - POSTGRES_DB=travis_ci_test
  web:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - .:/code/src
    ports:
      - "8000:8000"
    command: python3.6 ./manage.py runserver 0.0.0.0:8000
