# Generated by Django 2.2.6 on 2019-10-24 15:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('terra_accounts', '0006_auto_20190912_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraPermission',
            fields=[
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Permission')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
