# Generated by Django 3.1.3 on 2021-05-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra_accounts', '0009_terrapermission_module'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='terrapermission',
            managers=[
            ],
        ),
    ]
